import {illustrationMaterial,characterLight} from './character_material.js';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const stage=$('#stage'),canvas=$('#canvas');let renderer,controls,model,modelRevision='',mode='3d',lastData=null,view='front',pending=0,visible=true,style='illustration';
window.__renderFrames=0;const worldLight=new THREE.Vector3(-.45,.8,.9).normalize();
const scene=new THREE.Scene(),camera=new THREE.OrthographicCamera(-3,3,4,-4,.01,100);camera.position.set(.1,3.8,15);
try{renderer=new THREE.WebGLRenderer({canvas,alpha:true,antialias:true,powerPreference:'high-performance'});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.outputColorSpace=THREE.SRGBColorSpace;renderer.toneMapping=THREE.NoToneMapping;controls=new OrbitControls(camera,canvas);controls.target.set(.12,3.64,0);controls.enableDamping=true;controls.dampingFactor=.08;controls.minZoom=.5;controls.maxZoom=4.5;controls.autoRotateSpeed=.65;controls.maxPolarAngle=Math.PI*.89;controls.update();scene.add(new THREE.AmbientLight(0xffffff,1.35));const key=new THREE.DirectionalLight(0xfff4ee,2.0);key.position.set(-3,8,5);scene.add(key);const fill=new THREE.DirectionalLight(0xc6d8ff,.65);fill.position.set(4,4,3);scene.add(fill);const rim=new THREE.DirectionalLight(0xd8cbff,1.2);rim.position.set(1,7,-4);scene.add(rim);new ResizeObserver(resize).observe(stage);resize();controls.addEventListener('change',invalidate);new IntersectionObserver(e=>{visible=e[0].isIntersecting;if(visible)invalidate();}).observe(stage);invalidate();}catch(error){console.error(error);mode='render';$('#mode3d').disabled=true;$('#modelstate').textContent='RENDER FALLBACK';}
function resize(){if(!renderer)return;const w=stage.clientWidth,h=stage.clientHeight,a=w/h;const v=7.8;camera.left=-v*a/2;camera.right=v*a/2;camera.top=v/2;camera.bottom=-v/2;camera.updateProjectionMatrix();renderer.setSize(w,h,false);invalidate();}
function setView(name){if(!controls)return;view=name;const target=name==='face'?new THREE.Vector3(0,6.39,0):new THREE.Vector3(.12,3.64,0);controls.target.copy(target);camera.zoom=name==='face'?3.25:1;const offsets={front:[0,.15,15],quarter:[7,.6,13],side:[15,.5,0],back:[0,.5,-15],face:[0,.06,15]};camera.position.copy(target).add(new THREE.Vector3(...offsets[name]));camera.updateProjectionMatrix();controls.update();document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===name));$('#viewlabel').textContent=name.toUpperCase()+' / ORTHOGRAPHIC';invalidate();}
function setMode(v){mode=v;$('#canvas').hidden=v!=='3d';$('#hero-render').hidden=v!=='render';$('#mode3d').classList.toggle('active',v==='3d');$('#moderender').classList.toggle('active',v==='render');if(lastData)$('#waiting').hidden=!!(v==='3d'?model:lastData.renders?.length);}
$('#mode3d').onclick=()=>setMode('3d');$('#moderender').onclick=()=>setMode('render');document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setMode('3d');setView(b.dataset.view)});$('#reset').onclick=()=>setView('front');$('#rotate').onclick=()=>{if(!controls)return;controls.autoRotate=!controls.autoRotate;$('#rotate').classList.toggle('active',controls.autoRotate);invalidate()};$('#fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else stage.requestFullscreen?.()};
function dispose(root){root.traverse(o=>{o.geometry?.dispose();if(o.material){for(const m of Array.isArray(o.material)?o.material:[o.material])m.dispose();}});}
async function loadModel(path,rev){if(!renderer||rev===modelRevision)return;modelRevision=rev;$('#modelstate').textContent='LOADING GLB…';try{const gltf=await new GLTFLoader().loadAsync(path+'?v='+encodeURIComponent(rev));if(model){scene.remove(model);dispose(model);}model=gltf.scene;scene.add(model);let tri=0;model.traverse(o=>{if(o.isMesh){o.frustumCulled=true;o.userData.original=o.material;o.userData.illustration=Array.isArray(o.material)?o.material.map(illustrationMaterial):illustrationMaterial(o.material);o.material=o.userData.illustration;tri+=(o.geometry.index?.count||o.geometry.attributes.position.count)/3;}});$('#triangles').textContent=(tri/1000).toFixed(0)+'k';$('#modelstate').textContent='LIVE 3D · '+rev;$('#waiting').hidden=true;window.__modelReady=true;window.__modelTriangles=tri;setView(view);}catch(e){console.error(e);modelRevision='';$('#modelstate').textContent='EXPORT IN PROGRESS';}}
async function refresh(){try{const r=await fetch('status.json?t='+Date.now(),{cache:'no-store'});if(!r.ok)throw Error(r.status);const d=await r.json();const changed=JSON.stringify(d)!==JSON.stringify(lastData);lastData=d;$('#connection').textContent=location.hostname.endsWith('github.io')?'PUBLISHED BUILD':'LIVE WORKSPACE';if(!changed)return;$('#revision').textContent=d.revision||'R00';$('#phase').textContent=d.phase||'Construction in progress';$('#status-note').textContent=d.note||'';$('#iteration').textContent=d.iterations||0;$('#score').textContent=d.score==null?'—':d.score+'/100';$('#projectpath').textContent='Project: '+d.projectPath;$('#buildpath').textContent='Build: '+d.buildPath;$('#updated').textContent='UPDATED '+new Date(d.updated).toLocaleString();$('#downloads').innerHTML=(d.files||[]).map(f=>`<div class="download"><a href="${esc(f.url)}" download><span>${esc(f.label)} ↗</span><small>${esc(f.size||'')}</small></a><code class="file-path">${esc(f.path)}</code></div>`).join('')||'<p class="muted">Exports appear here when ready.</p>';$('#renders').innerHTML=(d.renders||[]).map(f=>`<article class="render-card"><a href="${esc(f.url)}?v=${esc(d.revision)}" target="_blank" rel="noopener"><img src="${esc(f.url)}?v=${esc(d.revision)}" loading="lazy" alt="${esc(f.label)}"></a><div class="caption"><span>${esc(f.label)}</span><span>${esc(f.revision||d.revision)}</span></div><code class="file-path">${esc(f.path)}</code></article>`).join('')||'<p class="muted">Inspection views appear after the first render.</p>';$('#journal').innerHTML=(d.journal||[]).slice().reverse().map(j=>`<article class="journal-entry"><div class="rev">${esc(j.revision)}</div><div><h3>${esc(j.title)}</h3><p>${esc(j.notes)}</p>${j.image?`<a href="${esc(j.image)}" target="_blank" rel="noopener">Inspect this pass ↗</a>`:''}<br><small>${esc(j.time||'')} · ${esc(j.kind||'Visual review')}</small></div><div class="journal-score">${j.score==null?'—':esc(j.score)}<span>/100</span></div></article>`).join('')||'<div class="journal-empty">The first completed build-and-review cycle will be recorded here.</div>';if(d.renders?.length){$('#hero-render').src=d.renders[0].url+'?v='+d.revision;if(!renderer)setMode('render');}if(d.model)loadModel(d.model,d.modelRevision||d.revision);setMode(mode);invalidate();}catch(e){$('#connection').textContent='RECONNECTING';}}
refresh();setInterval(refresh,8000);window.addEventListener('keydown',e=>{if(e.key==='0')setView('front');});

function invalidate(){if(!pending&&visible&&!document.hidden&&mode==='3d')pending=requestAnimationFrame(draw);}
function draw(){pending=0;if(!visible||document.hidden||mode!=='3d'||!renderer)return;controls.update();camera.updateMatrixWorld();characterLight.value.copy(worldLight).transformDirection(camera.matrixWorldInverse);renderer.render(scene,camera);window.__drawCalls=renderer.info.render.calls;window.__geometryCount=renderer.info.memory.geometries;window.__renderFrames++;if(controls.autoRotate)invalidate();}
$('#shading').onclick=()=>{style=style==='illustration'?'studio':'illustration';model?.traverse(o=>{if(o.isMesh)o.material=style==='illustration'?o.userData.illustration:o.userData.original;});$('#shading').textContent=style==='illustration'?'Illustration':'Studio lighting';invalidate();};
document.addEventListener('visibilitychange',()=>{if(!document.hidden)invalidate();});

// Numerical geometry candidates are separate from the rendered-review counter.
const contactStatus=document.createElement('p');contactStatus.id='contact-progress';contactStatus.className='contact-progress';$('#status-note').after(contactStatus);
async function updateContactProgress(){try{const response=await fetch('assets/contact_search_progress.json?t='+Date.now(),{cache:'no-store'});if(!response.ok)return;const d=await response.json();contactStatus.textContent='Hand contact: '+Number(d.completed).toLocaleString()+' / '+Number(d.requested).toLocaleString()+' candidate geometry tests · '+d.stage;}catch{}}
updateContactProgress();setInterval(updateContactProgress,8000);
